language: node_js
cache: yarn
node_js:
- node
- '10'
- '8'
os:
- linux
- osx
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
script:
- npm test
after_success:
- yarn coverage
jobs:
  include:
  - stage: release
    if: branch IN (master, next)
    node_js: node
    script:
    - npm run build
    - npx semantic-release
    env:
    - secure: jHMdOpn9v07m3wPLMA0V9OoabrdjPeBWsyhUDNK2PjuC/fkpvfjdyrvw9HDpncjysgfqwAWT+zUUBe5x1UMTH5n+ok1aJEnTV33tHmx8RliyqgUng1yqYM36d3tfnwSmyCRaApkpF5xMEzCN+jaTJkrJlNDlLNt/XPnIkawHBCvFSBOkqeHlxi+DvgQFrxjJXSxnNuWmjsg2UNGTAa8gKd1F8mARIMhyqvYjme4rdV1a0MogUARZr44NlhLrPtRcQzMm+/becKZJnWKrd4NlVYL7Eu6etQ/1KZ1szfvW96m4IDQZffU2cQM/Clgdds6Uuoy2IAFzG1ILSDsWBfeD11I/u6qJmThPpUWbjxqpXXIltdGftcQ/fbEuj7F5pRWAbQOWE7c91UWniAGCGojAf8mbcLPk4n0/dYPX07mhds62f+Yw2urXq6T07UNHPw+o5Arn6tWeRiqvKx2/x70H8hDzcoHkE9PLHAPRFcH8tAjjjW+8JXLLO3O9cVUWps8nyyItyzDearHqH62pFpiyPjmoM/JvPGDH3qzP9ZhbWNh2lfsWEpeHJQULtftgeiRS00hYQRe+bGMY5X1hVr4XYz0uQWofgQ9XnwmpmLN7/pHqdVD3FoX9WrBKedyTSxBMSezalnPZsm3YEXd8II61SixUBDsliP8dbeZnHfOHbKw=
    - secure: Pwr2Bzr1Q6Nsw97QRVjmwb3zacOt3frW7EpDKxO9pg4Px+VOKilUvUHKCSQhayMShZz/6jLkLIwoTyQvkDBcUEn90WZ/VXP04DvTOmu62aVjWe5Of9/Hu/VQWdIB46r/UbTzsH7P+QliPI4606AvHHBm8CsmAcNqtMNu+xh4qtiHQPCYVvnA3QQngun6Es5Ytz0BUwB5uuzhGqOFdlVDVatK5LgyhOs7LjjJSZ4l1zR3Ru7Gx0Fek8ntat8bm7bJ9ZqG2MdMqnwa2uG8kwfSsKkHv9q7quBA7SngI4XaNOQVpOsDhNBk+n/DOJYxUbDCt9Rmn8LN32GP8ymclFXfwEyT0+I2Jc06mo6kWh6rI15fUNq4++PKCWDnbCpadN4Cxl0Sn+uAlykcZ1/j+uuvSHcdy/Q0kubTmPdh683ipqcjUHgbCd4lBqcpv3ax2CRxo5bxTfLJ1b/jKdheBkG7iKR7CmO1Qe6Qm6Wbi/CA4pWcmD9PyjKlOINZRcE3+UtIYJuuII02XC4kT/mAvJW1AZxnXg/DW4B9ZMJ6RuspasSxDeYLWb5Jf82BNoaje5mZekawDrO0Fprx5n65+Bu8VvBBoOp5o9NZdd9gn3+sviclrr0MRCEmb5nymV3avQvdidDUk960G0oaiXZ+blBP8MG5Ez9+z0T5+ke6JkCidFM=
